---
blank_issues_enabled: false

contact_links:
  - name: â” Ask a question
    url: https://github.com/JohnSnowLabs/langtest/discussions/new/choose
    about: Ask questions and discuss with other `LangTest` users or maintainers.

  - name: ğŸ™ Request help
    url: https://github.com/JohnSnowLabs/langtest/discussions/new/choose
    about: Ask the `LangTest` community for help.